# TODO
#  1) ADD A MAIN HANDLER FOR CHOOSING THE SIMULATION
#     OR AVOID THIS AND JUST RUN EACH SIMULATION MANUALLY
#
#  2.1) INTEGRATE PART 7
#
#  2.2) INTEGRATE PART 4 -> DONE
#
#  3) CHECK PART 3 TODOS  -> DONE
#
#  4) ADD PROGRESSBAR  -> DONE
#
#  5.1) BEAUTIFY PLOTS -> DONE
#
#  5.2) IMPROVE ANIMATED PLOTS
#
#  6) REMOVE USELESS PRINTS & COMMENTED CODE
#
#  7) REFACTOR DEBUG PRINTS
#
#  8) (no much time for this :() FIX A NAMING CONVENTION AND REWRITE CODE ACCORDINGLY: camelcase or snake case?
#
#  9) ESTIMATE NODE VISITS PROBABILITIES (monte carlo pagerank like approach)

